name: stellar_secrets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.4
  flutter_riverpod: ^2.4.9
  google_nav_bar: ^5.0.6
  hooks_riverpod: ^2.4.9
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MyIcons
      fonts:
      - asset: assets/MyIcons.ttf
  assets:
    - .env
    - assets/