name: stellar_secrets
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.4
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  internet_connection_checker: ^1.0.0+1
  photo_view: ^0.14.0
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: MyIcons
      fonts:
      - asset: assets/MyIcons.ttf
    - family: AclonicaRegular
      fonts:
      - asset: assets/Aclonica-Regular.ttf
  assets:
    - .env
    - assets/